spring.application.name=Chronos-Job-Scheduling
server.address=0.0.0.0
server.port=8080

# ===============================
# DATABASE CONFIG
# ===============================
#for localhost run
#spring.datasource.url=jdbc:postgresql://localhost:5432/chronos_db

#for docker run
spring.datasource.url=jdbc:postgresql://postgres:5432/chronos_db


spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Kafka Bootstrap Server for localhost
#spring.kafka.bootstrap-servers=localhost:9092

#kafka for docker run
spring.kafka.bootstrap-servers=kafka:9092



# ======================
# Producer Configuration
# ======================
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Disable type headers (optional but recommended)
spring.kafka.producer.properties.spring.json.add.type.headers=false

# ======================
# Consumer Configuration
# ======================
spring.kafka.consumer.group-id=job-group
spring.kafka.consumer.auto-offset-reset=earliest
#
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Trust all packages (or specify your package instead of "*")
#kafka.bootstrap-servers=kafka:9092



# Google OAuth
google.client.id=461612916595-olhggu0coriradspcet40abuducb98og.apps.googleusercontent.com

# (optional logging)
logging.level.org.springframework.security=DEBUG


# OTP Sending to phone for verification
twilio.accountSid=ACb26e163bf1251e429cc928e9b7fdf445
twilio.authToken=1b23cdbdbd7316b88edcf3fe3f54b123
twilio.phoneNumber=+16814333798


# ===============================
# CONNECTION POOL (HikariCP)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bhandarisagar248@gmail.com
spring.mail.password=srrp vmir cvxj dkcg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.mail.from=chronos@JobScheduling.com
app.mail.otp-expiry-minutes=5


#promethous configuration
management.endpoints.web.exposure.include=prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

